keys:
  - &pannu age1lp4pv3x95n2z4dh024f0ev05gnwrwf7n67z0c75cxa2vtus704msxgv700
  - &langsjo age1yezgssun7zpwt9g629dwjp8q3wddc8xp5k990ms7jtv6xku9yunq802pze
creation_rules:
  - path_regex: secrets/[^/]+.yaml$
    key_groups:
      - age:
        - *pannu
        - *langsjo
